name: SAMI
channels:
  - plotly
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
dependencies:
  - scanpy=1.9.1
  - matplotlib-base=3.6.3
  - matplotlib-inline=0.1.6
  - pandas=1.5.3
  - numpy=1.23.5
  - networkx=3.0
  - scipy=1.10.0
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - adjusttext=0.7.3.1
  - rpy2=3.5.11
  - anndata=0.8.0
  - r-base=4.2.3
  - python-igraph=0.10.3
  - leidenalg=0.9.1
  - pygraphviz=1.10
  - r-qs=0.25.5